### ISSUE TITLE
Anonymous opt-in telemetry

### ISSUE THREAD

**Issue by SuperAuguste** [zigtools/zls#1167]
## Roadmap

- [ ] Add a `zls.optInTelemetry` option
- [ ] Implement https://opentelemetry.io/ client in Zig
- [ ] Host some sort of telemetry server

## Metrics

  - [ ] Starts/stops w/ Zig/ZLS version, editor version, OS
  - [ ] Req/res kinds and times
  - [ ] Analysis times vs. file size
  - [ ] Errors and crashes

I know telemetry can be controversial in the OSS space but I feel that opt-in telemetry could help us substantially improve zls by targeting un(der)reported issues.
