### ISSUE TITLE
Fixing compatibility with latest Zig versions

### ISSUE THREAD

**Issue by FalsePattern** [zigtools/zls#1248]
Zls is currently not compilable on the latest commits of Zig (`0.11.0-dev.3735+a72d634b7` as of writing) due to 2 breaking changes:

## 1. JSON API rewrite

The JSON api of Zig was refactored in a recent commit: https://github.com/ziglang/zig/commit/32cb9462ffa0a9df7a080d67eaf3a5762173f742

Main changes:
- `std.json.parseFrom...(T: type...)` now return `std.json.Parsed(T)` instead of T
-  `json.parseFree(type, allocator, value)` was replaced by `std.json.Parsed.deinit(self: @This())`

This will require a somewhat extensive refactor of the way zls handles data loaded from json files.

Also affects the `tres` dependency

## 2. Casting operation renaming

All `@XtoY` casting operations were replaced with `@YFromX` in commit: https://github.com/ziglang/zig/commit/50339f595aa6ec96760b1cd9f8d0e0bfc3f167fc

Also affects the dependencies:
- tres https://github.com/ziglibs/tres
- diffz https://github.com/ziglibs/diffz
- binned_allocator https://gist.github.com/silversquirl/c1e4840048fdf48e669b6eac76d80634 it's a gist, so no good way to PR :(

This is a trivial fix, just have to run `zig fmt` on the dependencies, update them in zon, and then run `zig fmt` on zls too.

# Task list:

- [x] dependency upstream fixes
  - [x] diffz https://github.com/ziglibs/diffz/pull/14
  - [x] tres https://github.com/ziglibs/tres/pull/14
  - [ ] binned_allocator (Using a fork for now, upstream still hasn't merged the fix)
- [x] update zon to fixed dependencies
- [x] apply `zig fmt` to zls
- [ ] #1251
  - [x] Temporary `legacy_json.zig` compatibility layer

Working PR: https://github.com/zigtools/zls/pull/1249

**Comment by FalsePattern** [comment]
`binned_allocator` is a gist so a PR could not be made, but a fixed revision is available here:
https://gist.github.com/FalsePattern/48fded613c115e16e91c46db8642c7e4/75e3d5e6a0e0cf23dbf7abfe16831e23c38721bc

Once the other two dependencies are merged, we can proceed with the zon update.

**Comment by forinda** [comment]
Cannot build
```sh
error: Your Zig version v0.10.1 does not meet the minimum build requirement of v0.11.0-dev.3696+8d0a8c285
            @compileError(std.fmt.comptimePrint("Your Zig version v{} does not meet the minimum build requirement of v{}", .{ current_zig, min_zig }));
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    runBuild: /opt/apps/zig/lib/build_runner.zig:233:32
    usage__anon_5110: /opt/apps/zig/lib/build_runner.zig:242:13
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

**Comment by nullptrdevs** [comment]
@forinda 
> Cannot build

As you found out, building ZLS requires a newer version of Zig.
> And

Wait for this issue to be resolved as the changes required are somewhat extensive.

**Comment by FalsePattern** [comment]
For the json memory management part, i created a local test branch where i have:
- extracted the old `std.json.parseFree` function into a helper file
- implemented a `deepCopy` function that recursively copies json-like structs (creating newly allocated slices and pointers which are independent from the input value)
- Created wrapper `parseFrom...` functions, which read the json with the new API, defer deinit the returned `Parsed(T)`, and then return the deep copy of the value from the parsed json

The deep copy is needed here, because the new json api allocates conservatively, and does some weird "only copy if necessary" memory sharing with `[]const u8` slices that lead to double frees all over the place. (Maybe fixable long-term by replacing strings in the config autogenerator with regular mutable `[]u8`?)

After rewriting all `std.json.parseFrom...` and `parseFree` calls to these "compatibility" functions, zls works again with no complicated edits, as the behaviour of these deeply copied structs and the ported `parseFree` matches how the old version of the json library worked.

I will push said branch to my fork later today and link it here for review, this is not a perfect solution, but it's the simplest fix that avoids the complexity of a full migration to the new allocation behaviour.
